name: Deploy React Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t chaitu0428/ecom_ui:latest --build-arg VITE_APP_NODE_ENV=production --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} .
      - name: Publish Image to docker hub
        run: docker push chaitu0428/ecom_ui:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull chaitu0428/ecom_ui:latest
      - name: Delete old container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container chaitu0428/ecom_ui:latest
